# Site settings
title: Lauren McKenna
description: 'coffee drinker | iOS developer | runner | traveler'
#url: 'http://mckennatx.github.io/' 
#baseurl: '/home/'
# google_analytics: 'UA-XXXXXX-X'

author:
  name: 'Lauren McKenna'
  email: mckennaut@gmail.com
  twitter_username: mckennatx
  instagram_username: laurmckenna
  github_username:  mckennatx
  linkedin_username:  lmckenna

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: pygments

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
